LANGUAGES = ["en", "ru"]
LANGUAGE_NAMES = {"en": "English", "ru": "Русский"}

_current = "en"


def set_language(code):
    global _current
    if code in LOCALES:
        _current = code


def get_language():
    return _current


def cycle_language():
    idx = LANGUAGES.index(_current) if _current in LANGUAGES else 0
    set_language(LANGUAGES[(idx + 1) % len(LANGUAGES)])
    return _current


def t(key, **kwargs):
    table = LOCALES.get(_current) or LOCALES["en"]
    s = table.get(key)
    if s is None:
        s = LOCALES["en"].get(key, key)
    return s.format(**kwargs) if kwargs else s


LOCALES = {
    "en": {
        "menu.play": "Play",
        "menu.settings": "Settings",
        "menu.about": "About",
        "menu.quit": "Quit",
        "menu.feedback": "Bugs & ideas",
        "menu.tagline": "it has waited for you longer than you think",
        "menu.story": (
            "You woke up in an abandoned psychiatric ward. The power's out - without light "
            "you can't call the elevator down, and without the basement you can't get "
            "outside. It's close by. Collect fuses, power the panels, don't shine your "
            "light carelessly."
        ),
        "ui.back": "Back",
        "ui.understood": "Got it",
        "ui.yes_quit": "Yes, quit",
        "ui.no": "No",
        "ui.confirm_quit_title": "Are you sure you want to quit?",

        "pause.title": "PAUSED",
        "pause.resume": "Resume",
        "pause.to_menu": "Exit to menu",
        "pause.quit_game": "Quit game",

        "settings.title": "SETTINGS",
        "settings.tab_graphics": "GRAPHICS",
        "settings.tab_sound": "SOUND",
        "settings.tab_controls": "CONTROLS",
        "settings.tab_language": "LANGUAGE",
        "settings.tab_debug": "DEBUG",
        "settings.volume": "VOLUME",
        "settings.sfx_volume": "SOUND VOLUME",
        "settings.music_volume": "MUSIC VOLUME",
        "settings.mouse_sens_x": "MOUSE SENSITIVITY (H)",
        "settings.mouse_sens_y": "MOUSE SENSITIVITY (V)",
        "settings.view_distance": "VIEW DISTANCE",
        "settings.fullscreen": "Fullscreen",
        "settings.mic": "Microphone (listens to you)",
        "settings.mic_device_label": "INPUT DEVICE",
        "settings.mic_device_default": "System default",
        "settings.mic_device_missing": "Preferred device unavailable - using system default",
        "settings.mic_sensitivity": "MIC SENSITIVITY",
        "settings.mic_test": "Test level (speak into the mic)",
        "settings.mic_test_disabled": "Enable the microphone to test it",
        "settings.mic_test_error": "Couldn't open this device - try another one",
        "settings.language_label": "LANGUAGE",
        "settings.fps_limit_label": "FPS LIMIT",
        "settings.fps_unlimited": "unlimited",
        "settings.upscale_smoothing": "Smooth upscaling",
        "settings.quality_preset_label": "GRAPHICS QUALITY",
        "settings.quality_low": "Low",
        "settings.quality_medium": "Medium",
        "settings.quality_high": "High",
        "settings.quality_ultra": "Ultra",

        "controls.reset": "Reset",
        "controls.reset_done": "Controls reset to defaults",
        "controls.key_taken": "Key already used for \"{label}\"",
        "controls.press_key": "Press a key... (ESC - cancel)",

        "debug_hud.fps": "FPS counter",
        "debug_hud.coords": "Player coordinates",
        "debug_hud.monster": "Monster AI state",
        "debug_hud.seed": "Floor seed",
        "debug_hud.scares": "Dread / scare timing",
        "settings.debug_menu_only": "Coordinates / monster state / seed can only be toggled from the main menu, not mid-playthrough",

        "binding.forward": "Forward",
        "binding.back": "Back",
        "binding.left": "Left",
        "binding.right": "Right",
        "binding.sprint": "Sprint",
        "binding.crouch": "Crouch",
        "binding.flashlight": "Flashlight",
        "binding.interact": "Interact",

        "controls.legend_line1": "{move} - move    MOUSE - look    {sprint} - sprint    {crouch} - crouch",
        "controls.legend_line2": "{flashlight} - flashlight    {interact} - interact    ESC - pause",

        "warning.title": "WARNING",
        "warning.body": (
            "This game contains loud noises, jump scares, screen flicker and camera "
            "shake. Not recommended for people with epilepsy or heightened sensitivity "
            "to flashing lights."
        ),
        "warning.extra": "Disturbing visual and audio scenes are present.",

        "about.title": "ABOUT",
        "about.version": "Version {v}",
        "about.author": "Author: {a}",
        "credit.music": "Music",
        "about.body": (
            "Made solo with Python, pygame and moderngl - all graphics, textures and "
            "sound are generated by code, without a single external asset file."
        ),
        "about.links_label": "Links:",
        "about.link_web": "Website",
        "about.link_tg": "Telegram",
        "about.link_gh": "GitHub",

        "debug.title": "DEBUG: object showcase",
        "debug.hint": "Debug level: all items, walls and doors for inspection",
        "debug.peek_banner": "PREVIEW: {title}",
        "debug.peek_hint": "Floor preview: threat disabled. The portal by the entrance returns you to the hub.",
        "debug.collectible_label": "fuse",
        "debug.panel_label": "panel",
        "debug.exit_label": "exit",

        "gameover.caught_title": "YOU DIED",
        "gameover.caught_subtitle": "It turned out to be faster.",
        "gameover.sanity_title": "YOUR MIND GAVE OUT",
        "gameover.sanity_subtitle": "You're still down there, somewhere.",
        "end.restart": "Restart",
        "end.to_menu": "To menu",
        "end.survived": "Survived: {time}    Floor: {floor}/{total}",
        "end.stats_extra": "Notes read: {notes}    Batteries found: {batteries}    Scares survived: {scares}",

        "win.title": "YOU MADE IT OUT",
        "win.subtitle": "The gap in the fence closed behind you. Something stayed in the yard.",
        "win.time": "Escape time: {time}",

        "compass.n": "N", "compass.e": "E", "compass.s": "S", "compass.w": "W",

        "hud.flashlight": "FLASHLIGHT",
        "hud.stamina": "STAMINA",
        "hud.sanity": "SANITY",
        "hud.powered": "powered",
        "hud.carried": "{label}: {n} carried",
        "hud.panel_status": "{label}: {status}",
        "hud.installed_count": "{n}/{total} installed",
        "hud.exit_req": "{label}: {status}",
        "hud.have": "have it",
        "hud.dont_have": "don't have it",
        "hud.installing": "Installing...",

        "hint.something_missing": "Something is missing",
        "hint.cutters_picked": "Cutters picked up - now you can cut through the fence.",
        "hint.need_collectible": "Need {label} ({have}/{need})",
        "hint.exit_powered": "{label} powered.",

        "prompt.exit_hide": "[E] Exit hiding spot",
        "prompt.hide": "[E] Hide",
        "prompt.read_note": "[E] Read note",
        "note.title": "NOTE",
        "prompt.pickup": "[E] Pick up: {item}",
        "prompt.install_hold": "[HOLD E] Install {label} ({have}/{need})",
        "prompt.panel_need": "{panel}: {have}/{need}, need {label}",
        "prompt.exit_ready": "[E] {label}",
        "prompt.exit_no_power": "{label}: no power",
        "prompt.door_close": "[E] Close door",
        "prompt.door_open": "[E] Open  ·  [Hold] Peek",
        "prompt.portal": "[E] Portal: {target}",

        "pickup.battery": "battery",
        "pickup.fuse": "fuse",
        "pickup.valve_key": "valve key",

        "portal.floor0": "Floor 1",
        "portal.floor1": "Basement",
        "portal.floor2": "Backyard",
        "portal.hub": "Hub",

        "floor0.title": "WARD No. 9 - Residential Block",
        "floor0.collectible_label": "fuse",
        "floor0.panel_label": "fuse box",
        "floor0.exit_label": "elevator",
        "floor0.intro": "The power went out years ago. To call the elevator down,\nyou need to power the fuse box - bring it 3 fuses.",
        "floor0.descend_text": "THE ELEVATOR DESCENDS TO THE BASEMENT...",

        "floor1.title": "WARD No. 9 - Basement",
        "floor1.collectible_label": "valve key",
        "floor1.panel_label": "steam panel",
        "floor1.exit_label": "hatch upward",
        "floor1.intro": "This is where it lives. Three valves feed an old hatch to\nthe surface - without them, the cover won't budge.",
        "floor1.descend_text": "THE HATCH LEADS UP, TO OPEN AIR...",

        "floor2.title": "WARD No. 9 - Backyard",
        "floor2.collectible_label": "key",
        "floor2.panel_label": "shed lock",
        "floor2.panel_powered_text": "broken open",
        "floor2.exit_label": "gap in the fence",
        "floor2.exit_requires_label": "Need cutters",
        "floor2.exit_requires_item_label": "Cutters",
        "floor2.intro": (
            "The yard is ringed with barbed-wire fence. Past it is the forest.\n"
            "The shed holds a pair of cutters, but it's locked with 2 locks -\n"
            "find 2 keys to get inside."
        ),

        "note.floor0.0": "«...patients from Block B were moved downstairs again. Dr. Crane\nforbade asking why. The lights in Corridor B have been flickering for three weeks straight, and nobody comes to fix them...»",
        "note.floor0.1": "«Observation log, night 14: Patient No. 9 doesn't appear in any\nadmission records. Staff insist he's always been here. We stopped\ngoing down to the basement.»",
        "note.floor0.2": "«The panel in the utility room is dead - shut off deliberately, three times now.\nSomeone doesn't want the elevator down there working. Now I understand why.»",
        "note.floor0.3": "«Shift report, 03/14: the patient in Ward 12 asked again about\n‘the one who walks in the pipes.’ Staff have been joking about it for\nsix months. I don't find it funny.»",
        "note.floor0.4": "«Ward directive: being in Corridor B after lights-out without\nan escort is strictly forbidden. No reason is given in\nthe order.»",
        "note.floor0.5": "«Someone chalked on a locker door: ‘IT COUNTS YOUR STEPS.’\nWe erased it, of course. It was back the next day, in the\nsame hand.»",
        "note.floor0.6": "«Personal file: Patient No. 9 was admitted without a referral, without\nrelatives, without a birth date. The ‘diagnosis’ field is blank. We\nshould have asked who brought him here.»",
        "note.floor0.7": "«The nurse's aide quit after her third night shift. All she\nsaid was: ‘Someone answers when you call the patients by\ntheir names. It isn't them.’»",
        "note.floor0.8": "«3 a.m. rounds. Ward 9 is empty, door locked from the outside. As\nalways. As if he was never there at all - just a name\non the plate.»",
        "note.floor0.9": "«...they're moving patients downstairs in batches, like they're clearing\nthe floor. Nobody wants to say what for.»",

        "note.floor1.0": "«If you're reading this - don't keep your light on for long. It comes\nfor the light faster than it comes for sound. I thought it was the other way around. I was wrong, once.»",
        "note.floor1.1": "«The valves down here aren't holding back steam. Someone was venting ITS\nroom. Close them again when you leave. If you leave.»",
        "note.floor1.2": "«The boiler room hasn't run since winter, but someone comes down\nto check it every night. That name isn't on the shift log.»",
        "note.floor1.3": "«It's colder down here than it should be with the heating running.\nWe checked the pipes three times. The pipes are fine.»",
        "note.floor1.4": "«Sign on the utility corridor door: ‘AFTER 22:00 - TWO PEOPLE, NOT\nONE.’ Someone added underneath: ‘IT DIDN'T HELP ANYWAY.’»",
        "note.floor1.5": "«The basement inventory was halted by orders from above. The last\nentry in the log cuts off mid-sentence.»",
        "note.floor1.6": "«We stopped going for the old equipment in the far bay. Easier\nto write off the inventory than go there as two and\ncome back as one.»",
        "note.floor1.7": "«The cage in the corner of the utility bay was here before us. In\nthe records it isn't listed as medical equipment,\nor as anything else.»",
        "note.floor1.8": "«If the ventilation suddenly goes quiet, don't stop to ask why. Just\ngo back upstairs. It isn't a malfunction.»",
        "note.floor1.9": "«Someone welded the grate over the old crawlspace in the wall before\nI ever got here. It wasn't welded shut to keep us out.»",

        "note.floor2.0": "«The fence has been repaired three times this month. From the outside,\nnot the inside - like something's trying to get in, not out.»",
        "note.floor2.1": "«The shed used to have two locks for a reason. One was for thieves.\nThe second went on after the cutters disappeared, then turned up\nback in their spot, like nobody had ever touched them.»",
        "note.floor2.2": "«The forest past the fence isn't part of the hospital grounds on any\nofficial map. The land around it has been listed as ‘unsurveyed’\nfor forty years.»",
        "note.floor2.3": "«Escape attempt, night of July 9th: the patient made it to the gap in\nthe fence. He was found in the morning ten meters from it, facing\nthe building, not the forest.»",
        "note.floor2.4": "«The night watchman hasn't patrolled the yard after midnight since\nit became official policy. No reason is given in the order -\nonly the time.»",
        "note.floor2.5": "«Staff belongings turn up on the fence posts facing the forest\nsometimes. Not torn, not discarded - hung up, like they're on\ndisplay.»",
        "note.floor2.6": "«We keep the cutters in the shed instead of with security on purpose.\nIf it wants someone to leave through that gap - that decision\nshouldn't be its to make.»",
        "note.floor2.7": "«The yard is lit worse than the building, even though the wiring is\nnewer and up to current code. The lamps in the far corner burn out\nfaster than the rest - the same ones, every time.»",
    },
    "ru": {
        "menu.play": "Играть",
        "menu.settings": "Настройки",
        "menu.about": "Об игре",
        "menu.quit": "Выход",
        "menu.feedback": "Баги и идеи",
        "menu.tagline": "оно ждало тебя дольше, чем ты думаешь",
        "menu.story": (
            "Ты очнулся в заброшенном психиатрическом отделении. Электричества нет — "
            "без света не вызвать лифт в подвал, а из подвала единственный путь наружу. "
            "Оно где-то рядом. Ищи предохранители, запитывай щитки и старайся не "
            "светить фонарем впустую."
        ),
        "ui.back": "Назад",
        "ui.understood": "Понятно",
        "ui.yes_quit": "Да, выйти",
        "ui.no": "Нет",
        "ui.confirm_quit_title": "Точно хотите выйти?",

        "pause.title": "ПАУЗА",
        "pause.resume": "Продолжить",
        "pause.to_menu": "Выйти в меню",
        "pause.quit_game": "Выход из игры",

        "settings.title": "НАСТРОЙКИ",
        "settings.tab_graphics": "ГРАФИКА",
        "settings.tab_sound": "ЗВУК",
        "settings.tab_controls": "УПРАВЛЕНИЕ",
        "settings.tab_language": "ЯЗЫК",
        "settings.tab_debug": "ОТЛАДКА",
        "settings.volume": "ГРОМКОСТЬ",
        "settings.sfx_volume": "ГРОМКОСТЬ ЗВУКОВ",
        "settings.music_volume": "ГРОМКОСТЬ МУЗЫКИ",
        "settings.mouse_sens_x": "ЧУВСТВИТЕЛЬНОСТЬ МЫШИ (X)",
        "settings.mouse_sens_y": "ЧУВСТВИТЕЛЬНОСТЬ МЫШИ (Y)",
        "settings.view_distance": "ДАЛЬНОСТЬ ПРОРИСОВКИ",
        "settings.fullscreen": "Полноэкранный режим",
        "settings.mic": "Микрофон (слышит вас)",
        "settings.mic_device_label": "УСТРОЙСТВО ВВОДА",
        "settings.mic_device_default": "По умолчанию",
        "settings.mic_device_missing": "Устройство недоступно — используется системное по умолчанию",
        "settings.mic_sensitivity": "ЧУВСТВИТЕЛЬНОСТЬ МИКРОФОНА",
        "settings.mic_test": "Проверка микрофона (скажите что-нибудь)",
        "settings.mic_test_disabled": "Включите микрофон, чтобы проверить его",
        "settings.mic_test_error": "Не удалось открыть устройство — попробуйте другое",
        "settings.language_label": "ЯЗЫК",
        "settings.fps_limit_label": "ЛИМИТ FPS",
        "settings.fps_unlimited": "без ограничений",
        "settings.upscale_smoothing": "Сглаживание масштабирования",
        "settings.quality_preset_label": "КАЧЕСТВО ГРАФИКИ",
        "settings.quality_low": "Низкое",
        "settings.quality_medium": "Среднее",
        "settings.quality_high": "Высокое",
        "settings.quality_ultra": "Ультра",

        "controls.reset": "Сбросить",
        "controls.reset_done": "Настройки управления сброшены по умолчанию",
        "controls.key_taken": "Клавиша уже занята действием «{label}»",
        "controls.press_key": "Нажмите клавишу... (ESC — отмена)",

        "debug_hud.fps": "Счётчик FPS",
        "debug_hud.coords": "Координаты игрока",
        "debug_hud.monster": "Состояние ИИ монстра",
        "debug_hud.seed": "Сид генерации этажа",
        "debug_hud.scares": "Тайминг страха/испугов",
        "settings.debug_menu_only": "Координаты / состояние монстра / сид можно переключить только из главного меню, не во время игры",

        "binding.forward": "Вперёд",
        "binding.back": "Назад",
        "binding.left": "Влево",
        "binding.right": "Вправо",
        "binding.sprint": "Бег",
        "binding.crouch": "Присесть",
        "binding.flashlight": "Фонарик",
        "binding.interact": "Взаимодействие",

        "controls.legend_line1": "{move} - движение    МЫШЬ - осмотр    {sprint} - бег    {crouch} - присесть",
        "controls.legend_line2": "{flashlight} - фонарик    {interact} - взаимодействие    ESC - пауза",

        "warning.title": "ПРЕДУПРЕЖДЕНИЕ",
        "warning.body": (
            "В игре присутствуют громкие звуки, скримеры, мерцание экрана и тряска "
            "камеры. Не рекомендуется людям с эпилепсией или повышенной "
            "чувствительностью к вспышкам света."
        ),
        "warning.extra": "Также в игре есть пугающие визуальные и звуковые сцены.",

        "about.title": "ОБ ИГРЕ",
        "about.version": "Версия {v}",
        "about.author": "Автор: {a}",
        "credit.music": "Музыка",
        "about.body": (
            "Создано в одиночку на Python, pygame и moderngl — вся графика, текстуры "
            "и звуки генерируются кодом, без использования внешних ассетов."
        ),
        "about.links_label": "Ссылки:",
        "about.link_web": "Сайт",
        "about.link_tg": "Telegram",
        "about.link_gh": "GitHub",

        "debug.title": "DEBUG: просмотр объектов",
        "debug.hint": "Режим отладки: свободный осмотр всех предметов, стен и дверей",
        "debug.peek_banner": "ПРЕВЬЮ: {title}",
        "debug.peek_hint": "Осмотр этажа: угроза отключена. Портал у входа возвращает в хаб.",
        "debug.collectible_label": "предохранитель",
        "debug.panel_label": "щиток",
        "debug.exit_label": "выход",

        "gameover.caught_title": "ТЫ МЁРТВ",
        "gameover.caught_subtitle": "Оно оказалось быстрее.",
        "gameover.sanity_title": "ТВОЙ РАЗУМ НЕ ВЫДЕРЖАЛ",
        "gameover.sanity_subtitle": "Твой рассудок навсегда остался где-то там, внизу.",
        "end.restart": "Начать заново",
        "end.to_menu": "В главное меню",
        "end.survived": "Время выживания: {time}    Этаж: {floor}/{total}",
        "end.stats_extra": "Прочитано записок: {notes}    Найдено батареек: {batteries}    Пережито скримеров: {scares}",

        "win.title": "ТЫ ВЫБРАЛСЯ",
        "win.subtitle": "Брешь в заборе закрылась за твоей спиной. Что-то осталось стоять во дворе.",
        "win.time": "Время побега: {time}",

        "compass.n": "С", "compass.e": "В", "compass.s": "Ю", "compass.w": "З",

        "hud.flashlight": "ФОНАРИК",
        "hud.stamina": "ВЫНОСЛИВОСТЬ",
        "hud.sanity": "РАССУДОК",
        "hud.powered": "запитан",
        "hud.carried": "{label}: {n} в инвентаре",
        "hud.panel_status": "{label}: {status}",
        "hud.installed_count": "установлено: {n}/{total}",
        "hud.exit_req": "{label}: {status}",
        "hud.have": "в наличии",
        "hud.dont_have": "отсутствует",
        "hud.installing": "Установка...",

        "hint.something_missing": "Чего-то не хватает",
        "hint.cutters_picked": "Вы подобрали кусачки. Теперь можно проделать дыру в заборе.",
        "hint.need_collectible": "Требуется {label} ({have}/{need})",
        "hint.exit_powered": "{label}: питание подано.",

        "prompt.exit_hide": "[E] Выйти из укрытия",
        "prompt.hide": "[E] Спрятаться",
        "prompt.read_note": "[E] Прочитать записку",
        "note.title": "ЗАПИСКА",
        "prompt.pickup": "[E] Подобрать: {item}",
        "prompt.install_hold": "[ЗАЖАТЬ E] Вставить {label} ({have}/{need})",
        "prompt.panel_need": "{panel}: {have}/{need}, требуется {label}",
        "prompt.exit_ready": "[E] {label}",
        "prompt.exit_no_power": "{label}: нет питания",
        "prompt.door_close": "[E] Закрыть дверь",
        "prompt.door_open": "[E] Открыть  ·  [Удержать] Подглядеть",
        "prompt.portal": "[E] Портал: {target}",

        "pickup.battery": "батарейку",
        "pickup.fuse": "предохранитель",
        "pickup.valve_key": "вентильный ключ",

        "portal.floor0": "1-й этаж",
        "portal.floor1": "Подвал",
        "portal.floor2": "Задний двор",
        "portal.hub": "Хаб",

        "floor0.title": "ПАЛАТА №9 - Жилой корпус",
        "floor0.collectible_label": "предохранитель",
        "floor0.panel_label": "электрощиток",
        "floor0.exit_label": "лифт",
        "floor0.intro": "Свет отрубили много лет назад. Чтобы вызвать лифт,\nнужно подать питание на щиток — принеси к нему 3 предохранителя.",
        "floor0.descend_text": "ЛИФТ МЕДЛЕННО СПУСКАЕТСЯ В ПОДВАЛ...",

        "floor1.title": "ПАЛАТА №9 - Подвал",
        "floor1.collectible_label": "вентильный ключ",
        "floor1.panel_label": "паровой вентиль",
        "floor1.exit_label": "люк наверх",
        "floor1.intro": "Это его обитель. Отсюда три вентиля подают давление на старый\nлюк на поверхность — без них тяжелую крышку не сдвинуть.",
        "floor1.descend_text": "ЛЮК ВЕДЕТ НАВЕРХ, К СВЕЖЕМУ ВОЗДУХУ...",

        "floor2.title": "ПАЛАТА №9 - Задний двор",
        "floor2.collectible_label": "ключ",
        "floor2.panel_label": "замок на подсобке",
        "floor2.panel_powered_text": "сорван",
        "floor2.exit_label": "брешь в заборе",
        "floor2.exit_requires_label": "Нужны кусачки",
        "floor2.exit_requires_item_label": "Кусачки",
        "floor2.intro": (
            "Двор обнесен забором с колючей проволокой. Сразу за ним — лес.\n"
            "В подсобке лежат кусачки, но на двери висят два замка.\n"
            "Найди 2 ключа, чтобы попасть внутрь."
        ),

        "note.floor0.0": "«...пациентов из блока Б снова перевели на нижний уровень. Доктор Крейн\nзапретил задавать вопросы. Свет в коридоре Б безостановочно мерцает\nуже третью неделю, но электрики так и не пришли...»",
        "note.floor0.1": "«Журнал дежурств, 14-я ночь: Пациент №9 не числится ни в одном\nжурнале поступлений. Сотрудники утверждают, что он был здесь\nвсегда. Мы больше не спускаемся в подвал.»",
        "note.floor0.2": "«Щиток в подсобке обесточен. Кто-то целенаправленно вырывал провода\nуже трижды. Кто-то очень не хочет, чтобы лифт спускался вниз.\nТеперь я понимаю, почему.»",
        "note.floor0.3": "«Отчет о смене, 14.03: Пациент из 12-й палаты опять жаловался на\n«того, кто ползает по трубам». Санитары смеются над этими байками\nуже полгода. А мне вот совсем не смешно.»",
        "note.floor0.4": "«Внутреннее распоряжение: Нахождение в коридоре Б после отбоя\nбез сопровождения категорически запрещено. Никаких объяснений\nв приказе не приводится.»",
        "note.floor0.5": "«Кто-то нацарапал на дверце шкафчика: \"ОНО СЧИТАЕТ ШАГИ\".\nМы, конечно, всё стерли. На следующий день надпись появилась\nснова. Почерк тот же.»",
        "note.floor0.6": "«Из личного дела: Пациент №9 поступил без направления,\nбез родственников и без даты рождения. В графе \"диагноз\" —\nпрочерк. Надо было сразу узнать, кто его сюда привез.»",
        "note.floor0.7": "«Новенькая медсестра уволилась после третьей же ночной смены.\nБросила лишь одну фразу: \"Кто-то отзывается, когда зовешь\nпациентов по именам. И это не они\".»",
        "note.floor0.8": "«Обход в 03:00. Палата №9 пуста, дверь заперта снаружи.\nКак и всегда. Как будто его там никогда и не было —\nтолько имя на табличке.»",
        "note.floor0.9": "«...они переводят пациентов на нижний уровень целыми группами,\nбудто зачищают этаж. Но никто не хочет говорить, ради чего.»",

        "note.floor1.0": "«Если ты это читаешь — не включай фонарь надолго. На свет оно\nреагирует куда быстрее, чем на звук. Я думал, что всё наоборот.\nИ я ошибся. Один раз.»",
        "note.floor1.1": "«Эти вентили в подвале сдерживают вовсе не пар. Кто-то пытался\nпроветрить ЕГО камеру. Закрой их за собой, когда будешь уходить.\nЕсли вообще сможешь уйти.»",
        "note.floor1.2": "«Котельная простаивает с самой зимы, но кто-то каждую ночь\nспускается её проверять. Этой фамилии нет ни в одном графике дежурств.»",
        "note.floor1.3": "«Здесь слишком холодно для работающего на полную мощность отопления.\nМы трижды проверяли магистраль. С трубами всё в полном порядке.»",
        "note.floor1.4": "«Объявление на двери тех. коридора: \"ПОСЛЕ 22:00 ХОДИТЬ ТОЛЬКО\nПО ДВОЕ\". Ниже кто-то криво приписал маркером: \"И ВСЁ РАВНО\nНЕ ПОМОГЛО\".»",
        "note.floor1.5": "«Инвентаризация подвальных помещений экстренно свернута приказом\nсверху. Последняя запись в учетном журнале обрывается на полуслове.»",
        "note.floor1.6": "«Мы больше не ходим за старым оборудованием в дальний энергоблок.\nПроще списать всё имущество подчистую, чем спуститься туда вдвоем\nи вернуться одному.»",
        "note.floor1.7": "«Массивная клетка в углу тех-отсека стояла здесь еще до нас.\nПо документам она не проходит ни как медицинский инвентарь,\nни как что бы то ни было еще.»",
        "note.floor1.8": "«Если гул вентиляции вдруг стихнет — не пытайся выяснить причину.\nПросто беги наверх. Это не техническая неисправность.»",
        "note.floor1.9": "«Решетку старого лаза в стене намертво заварили еще до моего\nустройства на работу. И сделали это явно не для того, чтобы\nне впустить туда нас.»",

        "note.floor2.0": "«Забор латали трижды за этот месяц. И каждый раз с внешней стороны,\nа не с внутренней. Будто что-то отчаянно пытается прорваться внутрь,\nа не выбраться наружу.»",
        "note.floor2.1": "«Второй замок на сарай повесили не просто так. Первый был от воров.\nВторой добавили после того, как пропали кусачки, а затем вернулись\nна свое место, будто их никто и не трогал.»",
        "note.floor2.2": "«Лес за оградой не относится к территории больницы ни на одной\nофициальной карте. Эти земли числятся в кадастре как \"неучтенные\"\nвот уже сорок лет.»",
        "note.floor2.3": "«Попытка побега, ночь на 9 июля: пациент смог добраться до бреши\nв заборе. Утром его нашли в десяти метрах от нее. Он лежал\nлицом к корпусу, а не к лесу.»",
        "note.floor2.4": "«Сторожам официально запретили патрулировать двор после полуночи.\nВ письменном распоряжении нет никаких внятных причин —\nуказано лишь время.»",
        "note.floor2.5": "«На колючей проволоке со стороны леса иногда находят личные вещи\nперсонала. Не порванные в клочья, не брошенные в грязь, а\nаккуратно развешанные. Будто напоказ.»",
        "note.floor2.6": "«Мы специально держим кусачки в сарае, а не у охраны. Если оно\nвдруг решит, что кому-то пора выйти через эту прореху — пусть\nхотя бы это решение остается не за ним.»",
        "note.floor2.7": "«Двор освещен куда хуже корпусов, хотя проводку здесь меняли\nсовсем недавно и по новым ГОСТам. Лампы в дальнем углу\nперегорают быстрее остальных — и каждый раз одни и те же.»",
    },
}