import os
import sys
import tempfile

_here = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(_here))
sys.path.insert(0, _here)
os.environ.setdefault("SDL_VIDEODRIVER", "offscreen")
os.environ.setdefault("SDL_AUDIODRIVER", "dummy")

from tools.sandbox_settings import redirect
redirect()
from game import renderer3d as R
from game.props import PROP_DEFS

OUT = os.path.join(os.path.dirname(_here), "game", "mesh_tops.py")


def measure():
    import light_probe
    r = light_probe.Probe(out_dir=tempfile.mkdtemp()).renderer
    builders = dict(r._mesh_builders)
    out = {}
    for kind in sorted(PROP_DEFS):
        vs = R.VARIANT_MESH_BUILDERS.get(kind)
        if vs is None:
            b = builders.get(kind) or getattr(R, "build_%s_mesh" % kind, None)
            vs = (b,) if b else ()
        fracs = []
        for b in vs:
            try:
                data = b()
            except TypeError:
                fracs = []
                break
            fracs.append(round(float(data.reshape(-1, 11)[:, 2].max()), 4))
        if not fracs:
            continue
        out[kind] = fracs[0] if len(set(fracs)) == 1 else tuple(fracs)
    return out


def render(table):
    lines = ['"""Where each prop\'s mesh ends, as a fraction of its height.',
             '',
             'GENERATED by tools/measure_mesh_tops.py - do not edit by hand.',
             '',
             'This is what something set down on the prop stands at, unless',
             'props.SURFACE_TOP_FRAC has a deliberate opinion about that kind',
             '(a barrel\'s lid is inside its rim; a bench\'s seat is not its back).',
             '"""',
             '',
             'MESH_TOP_FRAC = {']
    for kind in sorted(table):
        v = table[kind]
        lines.append("    %r: %r," % (kind, v))
    lines.append("}")
    return "\n".join(lines) + "\n"


def main():
    table = measure()
    text = render(table)
    if "--write" in sys.argv:
        with open(OUT, "w", encoding="utf-8") as f:
            f.write(text)
        print("записано %d видов в %s" % (len(table), os.path.relpath(OUT)))
        return 0
    have = ""
    if os.path.exists(OUT):
        have = open(OUT, encoding="utf-8").read()
    if have == text:
        print("game/mesh_tops.py совпадает с мешами (%d видов)" % len(table))
        return 0
    print("game/mesh_tops.py УСТАРЕЛ - прогони с --write (%d видов)" % len(table))
    return 1


if __name__ == "__main__":
    sys.exit(main())
